// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_tHi6eM5K1BfrboRZ-Ow9cSM48inUbo',
    appId: '1:490211888328:web:ee2d7ab093d268460c69fd',
    messagingSenderId: '490211888328',
    projectId: 'iamincontrol-abde7',
    authDomain: 'iamincontrol-abde7.firebaseapp.com',
    storageBucket: 'iamincontrol-abde7.appspot.com',
    measurementId: 'G-ZNKY45GWDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC63YrDg9GgRjQ1FYoTPxUygvYJzpKXO4',
    appId: '1:490211888328:android:bb1e356fd092b1f00c69fd',
    messagingSenderId: '490211888328',
    projectId: 'iamincontrol-abde7',
    storageBucket: 'iamincontrol-abde7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEqpzL25lhsihFQ_p2CKxVC-ZJHUpJKjY',
    appId: '1:490211888328:ios:f368c5c4353224530c69fd',
    messagingSenderId: '490211888328',
    projectId: 'iamincontrol-abde7',
    storageBucket: 'iamincontrol-abde7.appspot.com',
    iosClientId: '490211888328-k307p4los76rre1ookrc86pec9lkkk2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectIAmInControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEqpzL25lhsihFQ_p2CKxVC-ZJHUpJKjY',
    appId: '1:490211888328:ios:f368c5c4353224530c69fd',
    messagingSenderId: '490211888328',
    projectId: 'iamincontrol-abde7',
    storageBucket: 'iamincontrol-abde7.appspot.com',
    iosClientId: '490211888328-k307p4los76rre1ookrc86pec9lkkk2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectIAmInControl',
  );
}
